<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1IAKUIC" failures="1" tests="10" name="Surefire test" time="22.498" errors="0" timestamp="2025-04-19T08:31:49 IST">
  <testcase classname="api.test.DDTTests" name="testPostUser" time="4.581"/>
  <testcase classname="api.test.DDTTests" name="testPostUser" time="1.563"/>
  <testcase classname="api.test.DDTTests" name="testPostUser" time="1.429"/>
  <testcase classname="api.test.DDTTests" name="testDeleteUser" time="1.472"/>
  <testcase classname="api.test.DDTTests" name="testDeleteUser" time="1.357"/>
  <testcase classname="api.test.DDTTests" name="testDeleteUser" time="1.404"/>
  <testcase classname="api.test.UserTests" name="testCreateUser" time="1.587"/>
  <testcase classname="api.test.UserTests" name="testgetUser" time="1.637"/>
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="3.392">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdateUser(UserTests.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="1.439"/>
</testsuite> <!-- Surefire test -->
